#%RAML 1.0 NamedExample
contact-response:
  value:
    Identification:
      firstName: Harish
      lastName: v
      DOB: '07/18/1990'
      gender: M
      title: Developer
    Address:
      - type: home
        number: 123
        street: 'main street'
        unit: '1a'
        city: richmond
        state: VA
        zipcode: '23233'
    Communication:
      - type: email
        value: 'harishv@test.com'
        preferred: true
      - type: cell
        value: '1234567890'
